syntax = "proto3";

option csharp_namespace = "Hotkey_Translator.OcrGrpc";

package ocr;

service OcrService {
  rpc Health(HealthRequest) returns (HealthResponse);
  rpc Recognize(OcrRequest) returns (OcrResponse);
}

message HealthRequest {
}

message HealthResponse {
  bool ready = 1;
  string message = 2;
}

message OcrRequest {
  bytes image = 1;
  string language = 2;
  string text_detection_model_name = 3;
  string text_recognition_model_name = 4;
  bool preserve_visual_lines = 5;
}

message OcrResponse {
  string json = 1;
}
