# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: translation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'translation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11translation.proto\x12\x0btranslation\"\x0f\n\rHealthRequest\"0\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"K\n\x10TranslateRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x13\n\x0bsource_lang\x18\x02 \x01(\t\x12\x13\n\x0btarget_lang\x18\x03 \x01(\t\"L\n\x11TranslateResponse\x12\x14\n\x0ctranslations\x18\x01 \x03(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x12\n\nlatency_ms\x18\x03 \x01(\x03\x32\xa3\x01\n\x12TranslationService\x12\x41\n\x06Health\x12\x1a.translation.HealthRequest\x1a\x1b.translation.HealthResponse\x12J\n\tTranslate\x12\x1d.translation.TranslateRequest\x1a\x1e.translation.TranslateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'translation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=34
  _globals['_HEALTHREQUEST']._serialized_end=49
  _globals['_HEALTHRESPONSE']._serialized_start=51
  _globals['_HEALTHRESPONSE']._serialized_end=99
  _globals['_TRANSLATEREQUEST']._serialized_start=101
  _globals['_TRANSLATEREQUEST']._serialized_end=176
  _globals['_TRANSLATERESPONSE']._serialized_start=178
  _globals['_TRANSLATERESPONSE']._serialized_end=254
  _globals['_TRANSLATIONSERVICE']._serialized_start=257
  _globals['_TRANSLATIONSERVICE']._serialized_end=420
# @@protoc_insertion_point(module_scope)
